"""Add meal preference and IP tracking to guest

FR-6: The system shall display an RSVP submission page. 5.1.1

Adds meal_preference and rsvp_ip_address columns for Phase 5.1.1 RSVP system.

Revision ID: 14cfb6b4f6bd
Revises: 76252b6b3d52
Create Date: 2025-10-15 03:56:16.656578+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cfb6b4f6bd'
down_revision: Union[str, None] = '76252b6b3d52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('meal_preference', sa.String(length=200), nullable=True))
    op.add_column('guests', sa.Column('rsvp_ip_address', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'rsvp_ip_address')
    op.drop_column('guests', 'meal_preference')
    # ### end Alembic commands ###