"""Add token tracking columns to Guest model

Revision ID: 76252b6b3d52
Revises: 6525f39b6e50
Create Date: 2025-10-09 21:07:44.803733+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76252b6b3d52'
down_revision: Union[str, None] = '6525f39b6e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guests', sa.Column('token_first_accessed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('guests', sa.Column('token_last_accessed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guests', 'token_last_accessed_at')
    op.drop_column('guests', 'token_first_accessed_at')
    op.drop_column('guests', 'token_expires_at')
    # ### end Alembic commands ###