"""add_seating_chart_models

FR-21: The system shall provide an interactive seating chart interface
Phase 6.1.1 Seating Chart Data Models

Revision ID: 704a4e491e23
Revises: 3ef72cb03241
Create Date: 2025-11-03 19:12:41.176509+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '704a4e491e23'
down_revision: Union[str, None] = '3ef72cb03241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seating_charts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('venue_width', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('venue_height', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('venue_unit', sa.Enum('METERS', 'FEET', name='venueunit'), nullable=False),
    sa.Column('background_image_url', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('chart_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seating_charts_event_id'), 'seating_charts', ['event_id'], unique=True)
    op.create_table('table_layouts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('seating_chart_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.String(length=100), nullable=False),
    sa.Column('table_type', sa.Enum('ROUND', 'RECTANGULAR', 'SQUARE', 'CUSTOM', name='tabletype'), nullable=False),
    sa.Column('x_position', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('y_position', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('width', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('height', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('rotation', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('table_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['seating_chart_id'], ['seating_charts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_layouts_seating_chart_id'), 'table_layouts', ['seating_chart_id'], unique=False)
    op.create_table('seat_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('table_layout_id', sa.UUID(), nullable=False),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('seat_position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_layout_id'], ['table_layouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_layout_id', 'guest_id', name='uq_table_guest'),
    sa.UniqueConstraint('table_layout_id', 'seat_number', name='uq_table_seat_number')
    )
    op.create_index(op.f('ix_seat_assignments_guest_id'), 'seat_assignments', ['guest_id'], unique=False)
    op.create_index(op.f('ix_seat_assignments_table_layout_id'), 'seat_assignments', ['table_layout_id'], unique=False)
    op.alter_column('guests', 'last_reminder_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('guests', 'thank_you_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'thank_you_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('guests', 'last_reminder_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_index(op.f('ix_seat_assignments_table_layout_id'), table_name='seat_assignments')
    op.drop_index(op.f('ix_seat_assignments_guest_id'), table_name='seat_assignments')
    op.drop_table('seat_assignments')
    op.drop_index(op.f('ix_table_layouts_seating_chart_id'), table_name='table_layouts')
    op.drop_table('table_layouts')
    op.drop_index(op.f('ix_seating_charts_event_id'), table_name='seating_charts')
    op.drop_table('seating_charts')
    # ### end Alembic commands ###